### ISSUE TITLE
Update qr library version to 1.0.0 

### ISSUE THREAD

**Issue by ThierryBrth** [lukef/qr.flutter#1]
Kevin Moore fix an annoying [bug](https://github.com/kevmoo/qr.dart/commit/3180d286be826efdd23b91a1924722d86d8e0127#diff-b55052ee21ed474e85f8e62debb06a20) in the last release of [qr](https://pub.dartlang.org/packages/qr). Can you update your dependency to have the last version of his library ?

Thanks !

**Comment by lukef** [comment]
Updated. Pub is processing.
