### ISSUE TITLE
Can someone please explain how to export the generated QR code as an image?

### ISSUE THREAD

**Issue by agharshit08** [lukef/qr.flutter#107]
I want to extract the image and store on the server as any normal image.

**Comment by renansa27** [comment]
Hello, how did u solve it?

**Comment by kamleshwebtech** [comment]
Without posting solution here, how can you close this issue??

**Comment by ibhanu** [comment]
> Without posting solution here, how can you close this issue??

Because the same issue have been asked multiple times.

**Comment by AirborneEagle** [comment]
For those who come across this in the future, [here](https://github.com/theyakka/qr.flutter/issues/115#issuecomment-736878067), and [here](https://github.com/theyakka/qr.flutter/issues/110#issuecomment-755277134) are some of the solutions that @ibhanu was alluding to, but did not provide.

Also, @lukef @lukepighetti  or any other maintainers, is the process of exporting to an image documented any place? I was unable to find it outside of git issues (including the two mentioned above).
