### ISSUE TITLE
Max number of character encodable in this implementation

### ISSUE THREAD

**Issue by eddywm** [lukef/qr.flutter#11]
Hi there,

I'd like to know the max number of characters possibly encodable, from what I tested it seemed to be locked at 78 string characters on the **L** level and depassing that number, it was crashing the widget.

Is there way to encode more than that, because 78 chars seem to be very low in some circumstances.

**Comment by Cretezy** [comment]
It seems like you need to raise the version (int).

See: http://www.qrcode.com/en/about/version.html

**Comment by lukef** [comment]
We wrap the awesome qr.dart library (https://github.com/kevmoo/qr.dart) and that library supports up to version 40. You should see the information that @Cretezy linked to determine which version you need. We don't automatically select the version based on the content size. We may support it in the future but I'm not actively looking into it.
