### ISSUE TITLE
QR image file 

### ISSUE THREAD

**Issue by CatalaHD** [lukef/qr.flutter#115]
**Is your feature request related to a problem? Please describe.**
I was trying to send this QR Code via `Share.shareFiles()` and this requires a `filePath (type String)` and I only can display the `QR Image` in the screen via `Widget`.

**Describe the solution you'd like**
Have a widget named `QRImage.file()` that saves the file and also returns or has the `filePath` in a property.

**Comment by kamleshwebtech** [comment]
do you have any documentation? how can we share, export and download drawed qr code image? Please share. Thanks.

**Comment by mrmko** [comment]
@kamleshwebtech 
Just had to work this out myself. It could do with something being included in the documentation on how to save a file. I use the following:

`ByteData qrBytes = await QrPainter(...)`

then convert it to a file by passing the byte data into the following function

`Future<File> saveImage(ByteData data, String name) async {

    //retrieve local path for device
    var path = await _localPath;

    final buffer = data.buffer;
    return new File('$path/$name.png').writeAsBytes(buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
  }`

see https://pub.dev/packages/path_provider for path stuff

**Comment by ramsmart-inno** [comment]
> @kamleshwebtech
> Just had to work this out myself. It could do with something being included in the documentation on how to save to file. I use the following:
> 
> `ByteData qrBytes = await QrPainter(...).toImageData(439); //439 being the size`
> 
> then convert it to a file by passing the byte data into the following function
> 
> ```
>  Future<File> saveImage(ByteData data, String name) async {
> 
>     //retrieve local path for device
>     var path = await _localPath;
> 
>     final buffer = data.buffer;
>     return new File('$path/$name.png').writeAsBytes(buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
>   }
> ```
> 
> see https://pub.dev/packages/path_provider for path stuff

Could you share the Full code for Reference?

**Comment by mrmko** [comment]
Generate the qr code as below

```
 //generate the qr code in bytes
    ByteData qrBytes = await QrPainter(
      data: "http://www.google.com",
      topLeftRadius: 10,
      bottomLeftRadius: 10,
      topRightRadius: 10,
      bottomRightRadius: 10,
      gapless: true,
      version: QrVersions.auto,
      color: Color.fromRGBO(0, 118, 191, 1),
      emptyColor: Colors.white,
    ).toImageData(878);

    //save the orignal image
    File qrFile = await SaveNetworkImage().saveImage(qrBytes, code.qid); //<--- see below for this function

    //upload the orignal qr
    String rawUrl = await FileUpload().uploadQrImage(qrFile);

    //set the raw url in qr object
    code.rawImageUrl = rawUrl;

    //add qr code
    await FirebaseFirestore.instance.collection("qrCodes").doc(code.qid).set(code.toJson(code));

```


Save the qr image
```
  Future<Io.File> saveImage(ByteData data, String name) async {
    //retrieve local path for device
    var path = await _localPath; //<-- see below function

    final buffer = data.buffer;
    return new Io.File('$path/$name.png').writeAsBytes(buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
  }
```


```
import 'package:path_provider/path_provider.dart';

Future<String> get _localPath async {
    final directory = await getApplicationDocumentsDirectory();

    return directory.path;
  }
```

**Comment by ramsmart-inno** [comment]
> Generate the qr code as below
> 
> ```
>  //generate the qr code in bytes
>     ByteData qrBytes = await QrPainter(
>       data: "http://www.google.com",
>       topLeftRadius: 10,
>       bottomLeftRadius: 10,
>       topRightRadius: 10,
>       bottomRightRadius: 10,
>       gapless: true,
>       version: QrVersions.auto,
>       color: Color.fromRGBO(0, 118, 191, 1),
>       emptyColor: Colors.white,
>     ).toImageData(878);
> 
>     //save the orignal image
>     File qrFile = await SaveNetworkImage().saveImage(qrBytes, code.qid); //<--- see below for this function
> 
>     //upload the orignal qr
>     String rawUrl = await FileUpload().uploadQrImage(qrFile);
> 
>     //set the raw url in qr object
>     code.rawImageUrl = rawUrl;
> 
>     //add qr code
>     await FirebaseFirestore.instance.collection("qrCodes").doc(code.qid).set(code.toJson(code));
> ```
> 
> Save the qr image
> 
> ```
>   Future<Io.File> saveImage(ByteData data, String name) async {
>     //retrieve local path for device
>     var path = await _localPath; //<-- see below function
> 
>     final buffer = data.buffer;
>     return new Io.File('$path/$name.png').writeAsBytes(buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
>   }
> ```
> 
> ```
> import 'package:path_provider/path_provider.dart';
> 
> Future<String> get _localPath async {
>     final directory = await getApplicationDocumentsDirectory();
> 
>     return directory.path;
>   }
> ```

Thank you @mrmko

**Comment by lukef** [comment]
This has been documented in other issues a lot. Closing.
