### ISSUE TITLE
java.lang.RuntimeException: Duplicate class com.google.protobuf.AbstractMessageLite found in modules

### ISSUE THREAD

**Issue by Arashnilu** [lukef/qr.flutter#118]
**Describe the bug**
I'm getting this error when i add qr_flutter package to pubspec.yaml file;
 **java.lang.RuntimeException: Duplicate class com.google.protobuf.AbstractMessageLite found in modules protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)**

Here are my packages:
cloud_firestore: ^0.13.1
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.3+3
  firebase_messaging: ^6.0.9
  firebase_storage: ^3.1.1
  provider: ^4.0.3
  uuid: ^2.0.4
  path_provider: ^1.6.0
  flutter_image_compress: ^0.6.5+1
  image_picker: ^0.6.3+1
  cached_network_image: ^2.0.0
  intl: ^0.16.1
barcode_scan: ^3.0.1
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
      ref: 2.0.0-dev.1

**Comment by lukef** [comment]
This is a Flutter issue and not related to qr.flutter. We don't use any protobuf classes.
