### ISSUE TITLE
Render issuse, when orientation is landscape

### ISSUE THREAD

**Issue by AndroidNils** [lukef/qr.flutter#14]
Hey,

i have a problem the qr.flutter Plugin... I want to show a qr-code in a AlertDialog. When the orientation == portrait is, is everything good. But when the orientation is landscape, the qr-code will not appear.

Error:
`I/flutter (31851): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (31851): The following assertion was thrown during performLayout():
I/flutter (31851): LayoutBuilder does not support returning intrinsic dimensions.
I/flutter (31851): Calculating the intrinsic dimensions would require running the layout callback speculatively, which
I/flutter (31851): might mutate the live render object tree.
I/flutter (31851): 
I/flutter (31851): When the exception was thrown, this was the stack:
I/flutter (31851): #0      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:167:9)
I/flutter (31851): #1      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics (package:flutter/src/widgets/layout_builder.dart:174:6)
I/flutter (31851): #2      _RenderLayoutBuilder.computeMaxIntrinsicWidth (package:flutter/src/widgets/layout_builder.dart:186:12)
I/flutter (31851): #3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter (31851): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter (31851): #5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter (31851): #6      RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter (31851): #7      RenderPadding.computeMaxIntrinsicWidth (package:flutter/src/rendering/shifted_box.dart:163:20)
I/flutter (31851): #8      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter (31851): #9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter (31851): #10     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter (31851): #11     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter (31851): #12     RenderFlex.computeMaxIntrinsicWidth.<anonymous closure> (package:flutter/src/rendering/flex.dart:575:60)
I/flutter (31851): #13     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:552:58)
I/flutter (31851): #14     RenderFlex.computeMaxIntrinsicWidth (package:flutter/src/rendering/flex.dart:572:12)
I/flutter (31851): #15     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter (31851): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter (31851): #17     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter (31851): #18     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter (31851): #19     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:617:36)
I/flutter (31851): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #28     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (31851): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #30     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
I/flutter (31851): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #32     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter (31851): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #34     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (31851): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #36     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (31851): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #51     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2881:13)
I/flutter (31851): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #53     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (31851): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #55     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (31851): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (31851): #65     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter (31851): #66     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (31851): #67     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (31851): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (31851): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (31851): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (31851): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (31851): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (31851): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (31851): #74     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (31851): #75     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (31851): 
I/flutter (31851): The following RenderObject was being processed when the exception was fired:
I/flutter (31851):   RenderIntrinsicWidth#48e1e relayoutBoundary=up6 NEEDS-LAYOUT
I/flutter (31851):   creator: IntrinsicWidth ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (31851):   _InkFeatures-[GlobalKey#533bf ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (31851):   CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ← ConstrainedBox ←
I/flutter (31851):   ⋯
I/flutter (31851):   parentData: <none> (can use size)
I/flutter (31851):   constraints: BoxConstraints(280.0<=w<=640.0, 0.0<=h<=288.0)
I/flutter (31851):   size: Size(280.0, 276.0)
I/flutter (31851):   stepWidth: null
I/flutter (31851):   stepHeight: null
I/flutter (31851): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (31851):   RenderFlex#ac62d relayoutBoundary=up7 NEEDS-LAYOUT
I/flutter (31851):     RenderPadding#fe54a relayoutBoundary=up8 NEEDS-LAYOUT
I/flutter (31851):       _RenderLayoutBuilder#6ac88 relayoutBoundary=up9 NEEDS-LAYOUT
I/flutter (31851):         RenderConstrainedBox#dbdf3 relayoutBoundary=up10
I/flutter (31851):           RenderPadding#58819
I/flutter (31851): ════════════════════════════════════════════════════════════════════════════════════════════════════`

My Code:
`class _QRCodeDialog extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      content: QrImage(
        data: "https://example.com",
        version: 3,
      ),
    );
  }
}`

Flutter doctor:
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.471], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

• No issues found!`

**Comment by lukef** [comment]
Do you know if this issue still exists? If so, is there a minimal test case I can look at?

**Comment by lukef** [comment]
Feel free to reopen if this is still an issue
