### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hejunbinlan** [lukef/qr.flutter#23]
new QrImage(
                  data: 'PDovDRoHAQBUQUEMBwAKQV9RHlOI3MQvVlZWVlZWMQwICldZCgteXgxbXl9fC1cKDFoLXghaDF5bVg8KXVoNMVxeX1deXF5fX11eXFpa',
                  size: 200.0,
                  errorCorrectionLevel: QrErrorCorrectLevel.L,
                )
报错

**Comment by lukef** [comment]
I'm not sure what the issue is here so I'm going to close this
