### ISSUE TITLE
Build Error in 1.1.16

### ISSUE THREAD

**Issue by pepie** [lukef/qr.flutter#25]
`Compiler message:
file:///<truncated>/.pub-cache/hosted/pub.dartlang.org/qr_flutter-1.1.6/lib/src/qr_painter.dart:101:25: Error: A value of type 'Future<Image>' can't be assigned to a variable of type 'Image'.
 - 'Future' is from 'dart:async'.
 - 'Image' is from 'dart:ui'.
Try changing the type of the left hand side, or casting the right hand side to 'Image'.
        toPicture(size).toImage(size.toInt(), size.toInt());`

**Comment by lukef** [comment]
This is documented in the README, has been the subject of quite a few issues (closed) and fixed in the `2.0.0-dev` branch.
