### ISSUE TITLE
Error in qr_painter (assigning Future<Image> to Image)

### ISSUE THREAD

**Issue by ammaratef45** [lukef/qr.flutter#28]
First of all, I want to thank you @lukef for this great library.

I got the following error while trying to use the `1.1.6` version

>Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/qr_flutter-1.1.6/lib/src/qr_painter.dart:101:25: Error: A value of type 'Future<Image>' can't be assigned to a variable of type 'Image'.
 'Future' is from 'dart:async'.
 'Image' is from 'dart:ui'.
Try changing the type of the left hand side, or casting the right hand side to 'Image'.
        toPicture(size).toImage(size.toInt(), size.toInt());

Trying `1.1.5` gives another error that `toByteData` method doesn't exist.

**Comment by lukef** [comment]
Please read the docs
