### ISSUE TITLE
Pick the appropriate QR code version based on content

### ISSUE THREAD

**Issue by modulovalue** [lukef/qr.flutter#3]
It would be really great if there was a mode that automatically adjusted the version depending on the length of the data provided with maybe a fallback widget for too long strings.

**Comment by lukef** [comment]
Good idea. I will look at adding it to qr.flutter or to qr.dart

**Comment by kelegorm** [comment]
That would be really handy. May be at first add separated calculator class.

**Comment by lukef** [comment]
I have a version of this that works now. I'll push it in a day or so.

**Comment by lukef** [comment]
Will be in 3.0.0 release (soon!)
