### ISSUE TITLE
Wrong image after upgrade

### ISSUE THREAD

**Issue by yostrokon** [lukef/qr.flutter#31]
Encoded info can't be recognized
In the image attached code at the left is from qr.dart example page, and code at the right is a generated by plugin

![screenshot from 2019-03-08 12-52-27](https://user-images.githubusercontent.com/41853897/54024663-12a73980-41a1-11e9-8289-89a62f71fa2b.png)

**Comment by lukef** [comment]
I seem to get the same result using both ..
![Untitled](https://user-images.githubusercontent.com/37941/59055420-9a591e80-884a-11e9-88b1-285876ec2829.png)

I'm going to close this issue for now. Please feel free to reopen.
