### ISSUE TITLE
QrInputTooLongException

### ISSUE THREAD

**Issue by silviucs** [lukef/qr.flutter#32]
I need to add a longer string, but I get this: [QR] ERROR - QrInputTooLongException: Input too long. 1116 > 640.

Is it a way to fix this?

**Comment by rrisque** [comment]
Hi @silviucs,

This input length cap is determined by which version QR code you are using. You can read more about QR versions here: https://www.qrcode.com/en/about/version.html

Try increasing your QR version by manually specifying like this:

`
QrImage(version=25, data: _dataString)
`

The link above also explains how to find the best version# based on the length of your data.

**Comment by lukef** [comment]
Thanks @rrisque!

**Comment by silviucs** [comment]
Thank you sir, it's working perfectly ;)
