### ISSUE TITLE
error in windows and linux but success in macos

### ISSUE THREAD

**Issue by ifin2000** [lukef/qr.flutter#33]
this is my pubspec.yaml

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  qr_flutter: ^2.0.0
```
my flutter : 
Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.648], locale en-ID)
    • Flutter version 1.1.8 at E:\flutter
    • Framework revision 985ccb6d14 (2 months ago), 2019-01-08 13:45:55 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)
 Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\syamsul\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\syamsul\AppData\Local\Android
    • Java binary at: C:\Program Files\Java\jdk1.8.0_172\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
VS Code (version 1.32.3)
    • VS Code at C:\Users\syamsul\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

my flutter script **same with flutter demo** (I have no edit anything)

**my error when** 
> flutter packages get

**is**
Running "flutter packages get" in elty2...                      
Invalid argument(s): Minimum version ("2.0.0") must be less than maximum ("2.0.0-0").
package:pub_semver/src/version_range.dart 67:7                            new VersionRange
package:pub/src/solver/reformat_ranges.dart 61:27                         _reformatTerm
package:pub/src/solver/reformat_ranges.dart 39:26                         reformatRanges.<fn>
dart:_internal                                                            ListIterable.toList
package:pub/src/solver/reformat_ranges.dart 40:12                         reformatRanges
package:pub/src/solver/reformat_ranges.dart 34:9                          reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                         reformatRanges
package:pub/src/solver/version_solver.dart 308:24                         VersionSolver._resolveConflict
package:pub/src/solver/version_solver.dart 131:27                         VersionSolver._propagate
package:pub/src/solver/version_solver.dart 96:9                           VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                         resolveVersions.<fn>
package:pub/src/log.dart 378:18                                           progress
package:pub/src/solver.dart 32:10                                         resolveVersions
package:pub/src/entrypoint.dart 203:24                                    Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 41:23                                    GetCommand.run
package:args/command_runner.dart 194:27                                   CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 171:39                                PubCommandRunner.runCommand.<fn>
dart:async                                                                new Future.sync
package:pub/src/utils.dart 109:12                                         captureErrors.<fn>
dart:async                                                                runZoned
package:pub/src/utils.dart 126:5                                          captureErrors
package:pub/src/command_runner.dart 171:13                                PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 119:11                                PubCommandRunner.run
===== asynchronous gap ===========================
C:\b\s\w\ir\k\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter packages get" in elty2...
pub get failed (1)

**Comment by lukef** [comment]
I'll have a look ASAP

**Comment by lukef** [comment]
Are you still having this issue? I haven't been able to replicate it on windows or linux (primary dev machine).

**Comment by lukef** [comment]
Feel free to reopen if it is still an issue.
