### ISSUE TITLE
Allow embedding of images within the QR code

### ISSUE THREAD

**Issue by lanjiachuan** [lukef/qr.flutter#37]
Is it possible to generate a QR code with a logo?

**Comment by pedromassango** [comment]
Is there a way that I can help on this?

**Comment by pedromassango** [comment]
@lukef Any update about this soluction?

**Comment by felpsio** [comment]
I'm also available to help if is there anything I can be useful :)

**Comment by lanjiachuan** [comment]
Can the logo come from the remote server?

**Comment by lukef** [comment]
@lanjiachuan - yes. The `QrImage` widget will support anything that extends `ImageProvider` (i.e.: `AssetImage`, `NetworkImage`, etc). The painter will only support a `dart:ui.Image` though, so if you use `QrPainter` directly then you will need to manually do the load.

**Comment by lukef** [comment]
Progress update: I'm now happy with the mechanism + interfaces for the image stuff. I now just need to tidy it up and add some configuration options and it'll be done.

**Comment by lanjiachuan** [comment]
The argument type 'FileImage' can't be assigned to the parameter type 'Image'.
The code in test reported an error. Can you provide a demo that can be run?

**Comment by lukef** [comment]
Fixed in 3.0. It should be up on pub now.

**Comment by lukef** [comment]
@lanjiachuan - there is an example in the README now.

**Comment by abdullah4one** [comment]
It generate invalid QrCode
