### ISSUE TITLE
Can't generate QR code for encrypted string

### ISSUE THREAD

**Issue by kishanravindra** [lukef/qr.flutter#38]
Hi Guys, 
I'm trying to generate QR code for encrypted String. But QR code is not generating properly.
```
MITeqy6T8H6q0T003EEOFo4R5ifOoPWi7NyVJ1rwfKBkagKmGQP3jhODG+Hdxb0DWn7Gscib3QLlaiGbqt9zXchLl4gO/HOsDOM66nxjalrzDl3cpZOaVHzxDbJeuTf651CsHaohfs2y0cFBBAR5lYW2BoFdyjfber66HacfAVU3v1cWfukLVsALgd5WG2IlZIg+bM/OvCsylmgA4THbVqjuwsu7jItrKn9AtbsdBDJjTcgTfeMllgd0E6kvCrNB9tYRyKSogapwsln29SP/W7hMKX1Gb1Ep+DN6+GnCGfnJWnJrMo0c8DP0IDWvpUE3DV/WwFwUxtSVUzcybZYpJA==
````

**Comment by lukef** [comment]
You will need to use a value for `version` that is appropriate for the length of the string you are trying to store in the QR code. See here for more details: https://www.qrcode.com/en/about/version.html.
