### ISSUE TITLE
Way to Save Image to File?

### ISSUE THREAD

**Issue by Skquark** [lukef/qr.flutter#4]
I got the QrImage widget displaying the code great, but what I'd also like to do there is to save the generated code to a jpg, mainly so they can print it out for invite codes.  I tinkered around with it and couldn't find an easy way to save the image stream to a file.  Any suggestions?  Thanks.

**Comment by lukef** [comment]
This might be a good feature request for https://github.com/kevmoo/qr.dart. My package is a flutter specific wrapper over qr.dart. I could imagine it'd be useful generically for server applications as well.

**Comment by lukef** [comment]
Following up. You can use a `RepaintBoundary`. I tried that and it seems to work. See: https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/RenderRepaintBoundary/toImage.html. That link has an example for getting the png image data. You will then need to write some code to save the data to a file. Closing for now.

**Comment by kamleshwebtech** [comment]
how can we create jpg image? png image is transparent and mixed with background. Please share any suggestion.
