### ISSUE TITLE
How can i get the image data from QrImage?

### ISSUE THREAD

**Issue by EflakeEver** [lukef/qr.flutter#49]
I saw the property 'QrPainter' in QrImage class, it provided a method named 'toImageData' which may solved my problem.But it was private, can u help me?

**Comment by lukef** [comment]
`toImageData` is public in `2.1.0`. Are you using the latest version?

**Comment by EflakeEver** [comment]
@lukef toImageData is public, but QrPainter is still private. Please figure out if I was wrong

**Comment by EflakeEver** [comment]
@lukef by the way , i am using 2.1.0 now

**Comment by lukef** [comment]
`QrPainter` is public. They're both exported here: https://github.com/lukef/qr.flutter/blob/master/lib/qr_flutter.dart. 

Are you importing via `import 'package:qr_flutter/qr_flutter.dart';`?

I just created a new Flutter project and it works.

**Comment by lukef** [comment]
You can use the code from the painter test to see how to write to a file: https://github.com/lukef/qr.flutter/blob/master/test/painter_test.dart.

**Comment by EflakeEver** [comment]
@lukef Ok. It works, thanks for ur support.
