### ISSUE TITLE
Conform and return ImageProvider Class

### ISSUE THREAD

**Issue by kenthinson** [lukef/qr.flutter#57]
I would like to be able to generate a Qr code and get a return type of ImageProvider (https://api.flutter.dev/flutter/painting/ImageProvider-class.html). I'm trying to print the QR code using https://pub.dev/packages/printing

Optionally getting png data back would work instead.

**Comment by lukef** [comment]
`QrPainter` has a `toImageData` function that will return the bytes in png format. You should be able to use that. 

We haven't adhered to `ImageProvider` because of some technical reasons in the past but it might be possible now. I'll investigate.

**Comment by kenthinson** [comment]
@lukef I'll look into QrPainter. Thanks!

**Comment by kenthinson** [comment]
I was able to get it to work with QrPainter. Thanks for the help!
