### ISSUE TITLE
error when build

### ISSUE THREAD

**Issue by yafianshori** [lukef/qr.flutter#59]
Compiler message:
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/qr_flutter-3.0.0/lib/src/qr_image.dart:223:24: Error: Method not found: 'ImageStreamListener'.
    stream.addListener(ImageStreamListener((info, err) {
                       ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/qr_flutter-3.0.0/lib/src/qr_image.dart:223:24: Error: The method 'ImageStreamListener' isn't defined for the class '_QrImageState'.
 - '_QrImageState' is from 'package:qr_flutter/src/qr_image.dart' ('file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/qr_flutter-3.0.0/lib/src/qr_image.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageStreamListener'.
    stream.addListener(ImageStreamListener((info, err) {
                       ^^^^^^^^^^^^^^^^^^^

**Comment by lukef** [comment]
Can you provide information on what version of Flutter you're using please?

**Comment by yafianshori** [comment]
> Can you provide information on what version of Flutter you're using please?

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale id-ID)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.38.1)
[!] Connected device
    ! No devices available

do i need to import https://pub.dev/packages/qr ?

**Comment by kevinmathew94** [comment]
Same error here. Have you find a soluton ?

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.5.4-pre.17, on Microsoft Windows [Version 10.0.17134.829], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.38.1)
[√] Connected device (1 available)

• No issues found!

**Comment by lukef** [comment]
The issue is that the Flutter team made a breaking change to that part of the code. You will need to update Flutter to a higher version (if possible) or stay on the previous version of qr.flutter. The Flutter team has said previously that these types of breaks are to be expected and this is the way they want to move forward so I won't be doing anything to work around the issue. You just need to update Flutter. Sorry.

**Comment by kevinmathew94** [comment]
Thank You for that information.
