### ISSUE TITLE
There was an error when first running the qr image, after that the error will not appear again.

### ISSUE THREAD

**Issue by jasonlaw** [lukef/qr.flutter#62]
>> Unhandled exception

Error:

Bad state: Future already completed

Stack trace:

#0 _Completer.completeError (dart:async/future_impl.dart:21)
#1 _QrImageState._loadQrImage. (package:qr_flutter/src/qr_image.dart:226)
#2 ImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:369)
#3 MultiFrameImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:717)
#4 ImageStream.addListener (package:flutter/src/painting/image_stream.dart:262)
#5 _QrImageState._loadQrImage (package:qr_flutter/src/qr_image.dart:223)

#6 _QrImageState.build. (package:qr_flutter/src/qr_image.dart:159)
#7 _LayoutBuilderElement._layout. (package:flutter/src/widgets/layout_builder.dart:0)
#8 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328)
#9 _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:95)
#10 RenderObject.invokeLayoutCallback. (package:flutter/src/rendering/object.dart:1797)
#11 PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875)
#12 RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1797)
#13 RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:173)
#14 _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:240)
#15 RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
#16 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#17 RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
#18 RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259)
#19 RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
#20 RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744)
#21 RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
#22 RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392)
#23 RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
#24 RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206)
#25 RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
#26 MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142)
#27 _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:444)
#28 MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:244)
#29 RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356)
#30 RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
#31 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#32 RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
#33 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#34 _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232)
#35 RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
#36 RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510)
#37 RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1578)
#38 PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844)
#39 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:341)
#40 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:761)
#41 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280)
#42 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033)
#43 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975)
#44 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891)
#45 _rootRun (dart:async/zone.dart:1124)
#46 _CustomZone.run (dart:async/zone.dart:1021)
#47 _CustomZone.runGuarded (dart:async/zone.dart:923)
#48 _invoke (dart:ui/hooks.dart:249)
#49 _drawFrame (dart:ui/hooks.dart:207)

Device parameters:

id: PPR1.180610.011
androidId: dc69dcdfaa6ff9e7
board: universal8895
bootloader: G950FXXS5DSI1
brand: samsung
device: dreamlte
display: PPR1.180610.011.G950FXXS5DSI1
fingerprint: samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXS5DSI1:user/release-keys
hardware: samsungexynos8895
host: SWDG4517
isPsychicalDevice: true
manufacturer: samsung
model: SM-G950F
product: dreamltexx
tags: release-keys
type: user
versionBaseOs: samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXU5DSHC:user/release-keys
versionCodename: REL
versionIncremental: G950FXXS5DSI1
versionPreviewSdk: 0
versionRelase: 9
versionSdk: 28
versionSecurityPatch: 2019-09-01

**Comment by jasonlaw** [comment]
Update: Actually the error didn't go away but appear at the debug trace. The error occur if only we have an embedded image. The error always occur when set complete/error for the completer.
Really appreciate your help in looking into this issue.

![image](https://user-images.githubusercontent.com/107820/66128743-127cf880-e621-11e9-9ab6-006cca59eeed.png)

**Comment by lukef** [comment]
Let me take a look into this ASAP

**Comment by yuanzhiying** [comment]
I found this error yesterday. This is my output:
> $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.95, on Mac OS X 10.15 19A583, locale
    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
[✓] Connected device (1 available)

• No issues found!

**Comment by jasonlaw** [comment]
![image](https://user-images.githubusercontent.com/107820/66894669-9a9cce00-f023-11e9-861e-a132b6864cb3.png)

**Comment by jasonlaw** [comment]
PS C:\JSL\VIQCore\flutter\projects\viqcore_community> flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17134.1009], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\src\flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Connected device
    ! No devices available

**Comment by jasonlaw** [comment]
Any luck on the finding?

**Comment by lukef** [comment]
This should be fixed in the `3.0.2` release.

**Comment by lukef** [comment]
Next version will be `3.1.0` because I also needed to bump the Flutter version due to incompatibilities (breaking changes in Flutter).
