### ISSUE TITLE
The embeddedImage makes the QRCode unrecognizable

### ISSUE THREAD

**Issue by yintaibing** [lukef/qr.flutter#63]
The embeddedImage seems is just a overlay on the original qr code image, and then the qr code would be incomplete and unrecognizable...

**Comment by yintaibing** [comment]
More precisely, the reason is the size of embeddedImage is too large (qrCodeSize / 4). When I adjust its size to qrCodeSize / 5, the Wechat auto recognization works fine

**Comment by jasonlaw** [comment]
hi @yintaibing ,
Do you hit any error or see any error in the debug trace when using embeddedImage (please refer to #62)?
Do you mind share your code as I want to compare if I have done anything wrong.
Thank you very much.

**Comment by morrowyn** [comment]
I'm running into the same issue. using the values provided by the readme. Google lens is unable to detect the qr code.

```
QrImage(
  data: 'This QR code has an embedded image as well',
  version: QrVersions.auto,
  size: 320,
  gapless: false,
  embeddedImage: AssetImage('assets/images/my_embedded_image.png'),
  embeddedImageStyle: QrEmbeddedImageStyle(
    size: Size(80, 80),
  ),
)
```

**Comment by sheepdreamofandroids** [comment]
I think the problem (if it is one) is that the image is overlaid over the QR code, covering blocks in the center. If the error correction is high enough, those missing blocks will be corrected and the QR can still be read.
My intuition says that the center blocks should simply not be used, effectively creating a white square in the middle, which can then be used to embed the image without the need for extra error correction.
My intuition may be completely wrong though...

**Comment by Sheharyar566** [comment]
Yup the image is being overlayed leading to the issue.. and I think @sheepdreamofandroids makes sense to include the image in the qr code.

**Comment by sheepdreamofandroids** [comment]
Actually I've been doing a bit of research and I don't think there is a way to reserve unused space for a logo. This is simply something not foreseen by the standard.
As a workaround you can increase the errorCorrectionLevel so you can afford to distort some blocks. Which size of logo works with which level is a matter of experimentation though. Also take into account other causes of distortion like dirt and damage.

**Comment by lukef** [comment]
Please use the discussions or something for this as this issue has been raised a few times. You are correct that, yes, if you obscure 15-20% of the image then you are losing 15-20% of the data. Therefore you need to increase the error correction level to compensate. This is just the reality.
