### ISSUE TITLE
Android Scan Bar code get 12 digital barcode ,but iOS get 13 digital code

### ISSUE THREAD

**Issue by egeneration-me** [lukef/qr.flutter#67]
**Describe the bug**
I user this code to scan Bar Code

    controller = new QRReaderController(cameraDescription,
     ResolutionPreset.high,
        [CodeFormat.qr, 
        CodeFormat.pdf417,
        CodeFormat.upca,
        CodeFormat.upce,
        CodeFormat.ean13,
        CodeFormat.codabar,
        CodeFormat.aztec,
        CodeFormat.code128,
        CodeFormat.code39,
        CodeFormat.code93,
        CodeFormat.datamatrix,
        CodeFormat.itf,
        CodeFormat.ean8], onCodeRead);

1. use iPhone scan this barcode ,you will get bar code is 0018421010010
![WechatIMG48](https://user-images.githubusercontent.com/57591117/68622578-71475480-04a0-11ea-9982-ea37ba56a5c5.jpeg)

2. user Android device scan above barcode , you will get bar code is 018421010010

**Comment by lukef** [comment]
`QRReaderController` is in a different library. `qr_flutter` does not contain any scanning capabilities.

**Comment by netgfx** [comment]
@lukef do you have another library that does scan PDF417 barcodes?

**Comment by lukepighetti** [comment]
We do not publish any scanning utilities.
