### ISSUE TITLE
QrPainter is generating a different QRCode based on QrImage

### ISSUE THREAD

**Issue by ViniciusSossela** [lukef/qr.flutter#68]
Sample code:

```
Future<Uint8List> toQrImageData() async {
    final image = await QrPainter(
      data: data,
      version: QrVersions.auto,
      color: Colors.black,
      emptyColor: Colors.white
    ).toImageData(400);

    return image.buffer.asUint8List();
  }
```

The QRCode image from QrImage is this:

![WhatsApp Image 2019-11-30 at 19 12 59](https://user-images.githubusercontent.com/4993276/69906263-8d535d00-139f-11ea-8ee8-6f21a41bc60e.jpeg)

The QRCode image from QrPainter is this:

![WhatsApp Image 2019-11-30 at 19 34 49](https://user-images.githubusercontent.com/4993276/69906302-326e3580-13a0-11ea-9ce0-1822c3bd65e3.jpeg)

pub.yaml dependency

```
dependencies:
  qr_flutter: ^3.1.0
```

```


[✓] Flutter (Channel dev, v1.12.11, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.12.11 at /Users/viniciussossella/development/flutter
    • Framework revision f40dbf8ca0 (8 days ago), 2019-11-23 01:02:54 -0500
    • Engine revision d1cac77d5a
    • Dart version 2.7.0

```

**Comment by lukef** [comment]
Not sure why the finder patterns aren't rendering. Gapless will be FALSE by default on the painter (vs the image) but otherwise there shouldn't be any issue.

I implemented both in this gist using flutter `1.12.16` and it all works fine. Not sure if there are specific implementation issues. I tried your code separately and it worked for me also. 

Gist here: https://gist.github.com/lukef/a268b42e5c03fb950cbb11122c1ca44b

Looks like:
![Screenshot_1575158284](https://user-images.githubusercontent.com/37941/69907420-3c853980-138a-11ea-99b7-ee7279bf9ff0.png)

**Comment by ViniciusSossela** [comment]
@lukef Thanks for you explanation, it helped a lot. 

What was happing is that when I save the QRCode on the device as a file/image, it doesn't fill the QRCode with White color, it saves these 'white boxes'  with no color/transparent... And then when we try to share the qrcode (whatsapp, email...)... It fulfills the 'transparent' boxes with black.... I don't know why, but it happens...

Then I changed the old way:

```
Future<Uint8List> _getQrCodeBytes() async {
    final image = await QrPainter(
      data: data,
      version: QrVersions.auto,
      color: Colors.black,
      emptyColor: Colors.white,
      gapless: false,
    ).toImageData(400);

    return image.buffer.asUint8List();
  }
```

to this:

```
Future<Uint8List> _getQrCodeBytes() async {
    RenderRepaintBoundary boundary =
        globalKey.currentContext.findRenderObject();
    final image = await boundary.toImage();
    ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
    return byteData.buffer.asUint8List();
  }
```

And then my QRCode is saved with WHITE colors in the boxes pixels instead of transparent.... And it allow to share the QRCode too.

**Comment by lukef** [comment]
I see. The issue, i think, is that i'm not painting the inner rect of the finder pattern as i was working towards deprecating the empty color. The "fix" would be to paint the background a color before drawing the qr code on top. For now, I'll modify the code so that the empty color is drawn for the finder patterns until the final approach is fully defined.

**Comment by lawliet467** [comment]
@ViniciusSossela I tried your solution and it did not work for me.It turned all black when openning it

**Comment by lukef** [comment]
I have a fix. I'll try to get it up tomorrow!

**Comment by 4clear** [comment]
im waiting

**Comment by lukef** [comment]
`3.2.0` is live

**Comment by esmlima** [comment]
Hi @lukef , same issue here with version 4.0.0.

The QRImage code is below:
QrImage(
                    data: _data,
                    version: QrVersions.auto,
                    backgroundColor: Colors.white,
                    foregroundColor: Colors.black,
                    gapless: true,
                    size: 400)

Producing the following image:
![image](https://user-images.githubusercontent.com/110770797/188331260-ee948a01-534b-40dd-80fd-7eb15d5093a2.png)

The QRPainter code is below:
  Future<Uint8List> toQrImageData() async {
    final image = await QrPainter(
            data: _data,
            version: QrVersions.auto,
            color: Colors.black,
            emptyColor: Colors.white,
            gapless: true)
        .toImageData(400);

    return image!.buffer.asUint8List();
  }

Producing the following image (unrecognizable by the QR reader):
![image](https://user-images.githubusercontent.com/110770797/188331310-52e7a240-c399-43ea-8ece-746f9471b72f.png)

**Comment by nrallakis** [comment]
Any update regarding the painter not producing a valid QR code?
I have the same problem with @esmlima.

**Comment by domavaem** [comment]
I suggest not using QrVersions.auto.

I encountered a similar problem while exporting QR codes to PNG format. In my case, I utilized different QrVersions for each size:

 - For a size of 256, I used version 4.
 - For a size of 512, I used version 5.
 - For a size of 1024, it is recommended to use version 10.

I hope this information is helpful.
