### ISSUE TITLE
QrImage cann`t show in IOS

### ISSUE THREAD

**Issue by ChenYu29** [lukef/qr.flutter#69]
SimpleDialog(
      children: <Widget>[
        Center(
          child: RepaintBoundary(
            key: _renderObjectKey,
            child:
            QrImage(
              data: Constant.RemoteServerUrl+"loadPhoto?activityId="+widget.activtiyId,
              size: 200,
            ),
          ),
        ),
        FlatButton(
          color: Colors.white70,
          child: Text("保存二维码"),
          onPressed: () async {
            final result = await ImageGallerySaver.saveImage(await _getWidgetImage());
            print(result.toString());
            NavigatorUtils.goBack(context);
            if(result != null){
              Toast.show("保存成功");
            }else{
              Toast.show("保存失败");
            }
          },
        )
      ],
    );

**Comment by ChenYu29** [comment]
`SimpleDialog(
      children: <Widget>[
        Center(
          child: RepaintBoundary(
            key: _renderObjectKey,
            child:
            QrImage(
              data: Constant.RemoteServerUrl+"loadPhoto?activityId="+widget.activtiyId,
              size: 200,
            ),
          ),
        ),
        FlatButton(
          color: Colors.white70,
          child: Text("保存二维码"),
          onPressed: () async {
            final result = await ImageGallerySaver.saveImage(await _getWidgetImage());
            print(result.toString());
            NavigatorUtils.goBack(context);
            if(result != null){
              Toast.show("保存成功");
            }else{
              Toast.show("保存失败");
            }
          },
        )
      ],
    );`

**Comment by lukef** [comment]
I'm not sure what the issue is here. I need a bit more information to debug the issue.

**Comment by ChenYu29** [comment]
> I'm not sure what the issue is here. I need a bit more information to debug the issue.

I have solved the problem，In iOS,can`t use SimpleDialog show QrImage. I solved this problem with use Dialog
