### ISSUE TITLE
Version 1.1.2 based on advanced flutter codebase?

### ISSUE THREAD

**Issue by lubi888** [lukef/qr.flutter#7]
Hi Luke,
I'm not sure if I'm setup wrong but I don't think so. 
When I import 1.1.2 i get errors and so I have to go back to 1.1.1 just to get 0 errors when I run packages get.

```
Running "flutter packages upgrade" in ZZ         
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because ZZ depends on qr_flutter >=1.1.2 which requires SDK version >=2.0.0-dev.61.0 <3.0.0, version solving failed.
pub upgrade failed (1)

```
but i get no issues when i run 'flutter upgrade' other than that the main flutter repo has not been upgraded in 2 months. 

```
Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (2 months ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

```
I was just wondering if you're running an advanced flutter codebase to get 1.1.2 to work. I have to go back to 1.1.1 to get no yaml errors.

**Comment by lukef** [comment]
I'm using Flutter master but I thought the RC was > 58. I'll make 58 the minimum for now.

**Comment by lukef** [comment]
1.1.3 is posted. Let me know if you still have issues.
