### ISSUE TITLE
Integrate vCard as data in QrCode

### ISSUE THREAD

**Issue by ben04** [lukef/qr.flutter#72]
**Is your feature request related to a problem? Please describe.**
I'm currently working on an app, which should generate a QR code with contact information.

**Describe the solution you'd like**
It would be great if one could put a vCard in a QR code and also parse vCards from QR codes.

**Describe alternatives you've considered**
I could convert my object class to a string and put that in a QR code, but that somehow doesn't feel right..

**Comment by lukef** [comment]
QR codes can only contain strings, numbers and symbols (kanji, etc). They can't contain binary information. I'm not really sure what the ask is here. The alternative you suggested is probably the best implementation scenario.

**Comment by jcarboro94** [comment]
Same issue here!
