### ISSUE TITLE
QR with image could not be read by QR reader/scanner

### ISSUE THREAD

**Issue by CellCS** [lukef/qr.flutter#74]
If there is no errorCorrectionLevel: QrErrorCorrectLevel.Q, this QR (with an image inside) could not be recognized BarcodeScanner.scan. 

Following is based on your examples:

```
QrImage(
            data: codeText,
            version: QrVersions.auto,
            size: 320,
            gapless: false,
           // errorCorrectionLevel: QrErrorCorrectLevel.Q,
            embeddedImage: AssetImage('res/team.png'),
            embeddedImageStyle: QrEmbeddedImageStyle(
              size: Size(80, 80),
            ),
        ),
```

Unreadable: 
<img width="267" alt="readissue" src="https://user-images.githubusercontent.com/16886624/76648458-1e0c0e00-6535-11ea-9858-753bd26c31ff.png">

Readable (with errorCorrectionLevel: QrErrorCorrectLevel.Q,)
<img width="237" alt="readable" src="https://user-images.githubusercontent.com/16886624/76648487-295f3980-6535-11ea-80cf-c1f24fbf087b.png">

**Comment by lukef** [comment]
I don't think this is a bug. If you set an error correction level and version too low and then obscure a chunk of it with and image then it won't be readable. Right?

**Comment by CellCS** [comment]
Yes, I agree this is not a bug or issue.
Please delete.
Thanks.

**Comment by abdullah4one** [comment]
It is not readble
