### ISSUE TITLE
pub get failed 

### ISSUE THREAD

**Issue by ShengjieGeng** [lukef/qr.flutter#76]
![image](https://user-images.githubusercontent.com/18364968/77522158-bc498d80-6ebe-11ea-9a83-52348e48a689.png)
Hi,Lukef，I need your help,
please,
thanks anyway

**Comment by ShengjieGeng** [comment]
![image](https://user-images.githubusercontent.com/18364968/77523828-501c5900-6ec1-11ea-8a58-1e6290ef2e28.png)
and again!

**Comment by lukef** [comment]
I don't think this is related to the library. It seems to be a network issue.
