### ISSUE TITLE
中间图标不能编辑

### ISSUE THREAD

**Issue by ctluocc** [lukef/qr.flutter#77]
中间图标embeddedImage传一个ImageProvider，图标没法设置一些属性，比如圆角，边距，底色

**Comment by youlongxifeng** [comment]
中间图标embeddedImage覆盖了二维码内容，扫码成率降低了

**Comment by lukef** [comment]
Google translation: "The middle icon embeddedImage passes an ImageProvider, the icon can not set some properties, such as rounded corners, margins, background color"

**Comment by mrtehpeng** [comment]
The QR Code cannot be scanned when there is an embeddedImage

**Comment by lukef** [comment]
If you're using an embedded image with a low error correction setting then it is expected that this will happen. Either use a higher error correction setting, a higher version #, or both.
