### ISSUE TITLE
qr.flutter example not running as SPAN_EXCLUSIVE cannot have zero length

### ISSUE THREAD

**Issue by lubi888** [lukef/qr.flutter#8]
Hi Luke,

I'im rying to run the qr_flutter example but nothing is showing after I input the basics.

The page loads and there's a single blue line to enter data with a 'submit' button at the end.
I input text and then press submit. Nothing happens after than and only error signs.

```
I/hwaps   (24345): JNI_OnLoad
V/AudioManager(24345): playSoundEffect   effectType: 0
I/flutter (24345): [QR] WARN: width or height is zero. You should set a 'size' value or nest this painter in a Widget that defines a non-zero size
W/InputMethodManager(24345): startInputReason = 3
I/HwSecImmHelper(24345): mSecurityInputMethodService is null
E/SpannableStringBuilder(24345): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/chatty  (24345): uid=10248(u0_a248) com.example.ethsync011 identical 2 lines
E/SpannableStringBuilder(24345): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/flutter (24345): [QR] WARN: width or height is zero. You should set a 'size' value or nest this painter in a Widget that defines a non-zero size
I/flutter (24345): [QR] WARN: width or height is zero. You should set a 'size' value or nest this painter in a Widget that defines a non-zero size
I/flutter (24345): [QR] WARN: width or height is zero. You should set a 'size' value or nest this painter in a Widget that defines a non-zero size
```
I also notice that line 33 has another error,  bodyHeight is never used.

```
    final bodyHeight = MediaQuery.of(context).size.height -
        MediaQuery.of(context).viewInsets.bottom;
```
`The value of the local variable 'bodyHeight' isn't used`

Any ideas?

**Comment by lukef** [comment]
I'll take a look ASAP. It seems to be working here but I'll go over it all.

**Comment by lubi888** [comment]
Hi Luke,

That was quick. I wasn't expecting such a fast reply.

It was cool to just change one digit in the .yaml file , run package get, and have it work on the first go.

The screen comes up with a text to enter and there's already a default QR code that changes when submit is tapped. The qr screen square changes perfectly.

Thanks a bunch, Luke,

**Comment by lukef** [comment]
I aim to please!! :metal:  Thanks for letting me know.
