### ISSUE TITLE
Feature Request: Option to specify shape of QR modules. 

### ISSUE THREAD

**Issue by nacardin** [lukef/qr.flutter#80]
Hello,

How do you feel about allowing further customization? It would be nice to have the option to shape of QR modules and also the corner position markers. Perhaps it could also take in an arbitrary widget instead of the embedded image, so that something like an SVG image or button can be embedded. 

I'm trying to create a more aesthetically pleasing QR code like the one below.

![](https://i.pinimg.com/564x/6c/47/26/6c4726e26575aa5ae6086bbebbac1892.jpg)

Would like to hear your thoughts on this. Thanks!

**Comment by ankur2136** [comment]
#91 would let you change the shape of data modules and the eye frame.

**Comment by lukef** [comment]
Fixed in #94
