### ISSUE TITLE
How can i get this qr image for sharing?

### ISSUE THREAD

**Issue by Emarcode** [lukef/qr.flutter#83]
How can i get this image as a File object for sharing?

**Comment by lukef** [comment]
There are a bunch of Issues asking the same question that have the prescribed solution that are in "closed" status. You can find them by doing a search.

**Comment by Emarcode** [comment]
> 
> 
> There are a bunch of Issues asking the same question that have the prescribed solution that are in "closed" status. You can find them by doing a search.

Thanks a lot
I found the solution here:
[https://github.com/AhmedKhattab95/qr_code_sample/blob/master/lib/generate.dart](url)

**Comment by kamleshwebtech** [comment]
There is nothing on this url.
https://github.com/AhmedKhattab95/qr_code_sample/blob/master/lib/generate.dart

any other solution??

**Comment by Emarcode** [comment]
> There is nothing on this url.
> https://github.com/AhmedKhattab95/qr_code_sample/blob/master/lib/generate.dart
> 
> any other solution??

my problem was to get the qr image for sharing and this example solved my problem and extracted the image for sharing.
