### ISSUE TITLE
Sharing and converting QR code to Image

### ISSUE THREAD

**Issue by 00AhmedMokhtar00** [lukef/qr.flutter#88]
Hello, I read the feature of this awesome library that says: 

`Export to image data to save to file or use in memory`

but in the example doesn't define how to do so, can you help me please?

**Comment by mr0kaushik** [comment]
I also wanted to Save the QR Image but with some extra Widget, so here is what I followed:
1. Wraped the Required widget with [Screenshot Widget](https://pub.dev/packages/screenshot).
```
   Screenshot(
      controller: screenshotController,
      child: Container(
        padding: const EdgeInsets.all(10.0),
        child: ...
      ),
    );
```

2. Used `ScreenshotController` to take a screenshot and handed permission with [Permission Handler](https://pub.dev/packages/permission_handler).
```
    ScreenshotController screenshotController = ScreenshotController();

    screenshotController.capture().then((File imageFile) async {
      try {
        bool isGranted = await Permission.storage.isGranted;
        if (isGranted) {
          _saveToGallery(imageFile);
        } else {
          // Ask Permission
          PermissionStatus status = await Permission.storage.request();
          switch (status) {
            case PermissionStatus.undetermined:
              break;
            case PermissionStatus.granted:
              _saveToGallery(imageFile);
              break;
            case PermissionStatus.denied:
              debugPrint("Storage permission required to Save Image");
              break;
            case PermissionStatus.permanentlyDenied:
            case PermissionStatus.restricted:
              debugPrint("Storage permission required to Save Image, allow permissions in Settings");
              break;
          }
        }
      } catch (exp) {
        debugPrint("Storage Permission Error ${exp.toString()}");
      }
    }).catchError((err) {
      debugPrint("Image catchError ${err.toString()}");
    });
 
```
3. And finally saved the image using [Image Gallery Saver](https://pub.dev/packages/image_gallery_saver)
```
Future<void> _saveToGallery(File imageFile) async {
    try {
      final result =
          await ImageGallerySaver.saveImage(imageFile.readAsBytesSync());
      debugPrint("Image Stored Successfully !!");
    } on Exception catch (exp) {
      debugPrint("Image Exception ${exp.toString()}");
    }
  }

```

**Comment by lukef** [comment]
This has been answered many times in the closed issues. You can do a search for it and you'll find multiple examples. 

You can also look here: https://github.com/lukef/qr.flutter/blob/78e3bbe19f24a34fdbbb89e1e7b7f698f561ad28/test/image_test.dart.

You can also ask the question on StackOverflow so that the Issue Tracker isn't full of redundant (non-issue) questions.
