### ISSUE TITLE
Feature Request: qr 'read' with camera capabilities. Current 'qr read' plugins woefully inoperative. 

### ISSUE THREAD

**Issue by lubi888** [lukef/qr.flutter#9]
Hi Luke,

Request for QR flutter to add read capabilites, if its not too much trouble.

I'm sure you're busy with stuff but I'm having a rough time with what's available on pub.dartlang.org/flutter.

I've not been able to get any of these to work so far. All required a tweek of manifest.xml, build.gradle, app/build.gradle or pubspec.yaml, and that is just to make the given examples compile to an .apk. with gradle. It doesn't mean they have worked. Not a single one has activated the camera on my android phone.

I was going to write to the authors but then I realised that I would have to write to them all. I don't think I'm ready so start writing plugins so that leaves me seeking help elsewhere.

Various errors included (as i run these on Oreo 28 phone and 26-28 virtual devices):

'problems with minSDKVersion', having to set 'multiDexEnabled', etc.

```
qr_reader   0.1.3
https://pub.dartlang.org/packages/qr_reader#-readme-tab-
doesn't open|find camera.

qr_mobile_vision: ^0.0.7
'camera inactive' 'camera missing'
'I/flutter (19099): MissingPluginException(No implementation found for method start on channel com.github.rmtmckenzie/qr_mobile_vision)'

fast_qr_reader_view 0.1.2
https://pub.dartlang.org/packages/fast_qr_reader_view
'no camera found'. Scanning frame comes up as red box but no camera activated.

barcode_scan 0.0.4
https://pub.dartlang.org/packages/barcode_scan
no working

flutter_mobile_vision: ^0.1.1
'...refers, in an import, to the following library:
  package:flutter_mobile_vision_example/barcode_detail.dart
That library is in a package that is not known. Maybe you forgot to mention it in your pubspec.yaml file?'

```

Sadly, or happily, the only plugin that I can get a camera even launching on is Camera. The example worked 'straight out of the box' , unlike all the above plugins, once I added 'path_provider' and 'video_player'.
```
camera 0.2.1
https://pub.dartlang.org/packages/camera
I think this is because it has 'flutter team' as part of the contributors along with at least 4 other programmers.
```

Although there are numerous applications of QR squares with the app i'm tinkering with now I'd like for flutter to be able to 'read and create' ethereum addresses with visuals and camera scan capabilities. Using qr_flutter I can create visual ethereum addrs easily 
`['0x' + 40 alphanumeric chars, something like 'final RegExp ethAddExp = new RegExp(r'0x[a-fA-F0-9]{40}');'].`
Now I would also like for 2+ mobile devices to be easily able to exchange ethereum addresses with qr codes and camera access. Obviously, if I can get ethereum up and running it should be simple to add other blockchain coins with ease. 

Anyway, just something for you to think about , Luke, if you wanted to make yourself useful! :-) If I end up releasing this app to the wide world then it would be in a month or two. Is that enough time for you?

Otherwise, let me know if you have any other temporary fixes or think I should take another look at one of these programmers and plugins, if possible.

Ciao,

**Comment by Cretezy** [comment]
`barcode_scan` works beautifully with me. Did you follow the instructions for install? Did you restart after installing (has to compile native module)

**Comment by lukef** [comment]
I have a working Flutter Widget to do QR code scanning that doesn't require launching a native window but I'm not ready to release it. I am planning to release it as a separate library because I'd rather not add unnecessary complexity to this library if you just want to generate a QR code. Stay tuned.

**Comment by gedw99** [comment]
hey @lukef 
I am also in the same predicament in that i also need to scan. Not using native window is a huge bonus actually because it will probably also work on ChromeOS.

Any code to look at yet ? I can probably help

**Comment by joeblew99** [comment]
@lukef Sorry to bug you. Am going through trying out readers and found one that sort of works :)
If you have dropped the idea of the reader, its cool, but can you let me know.

I am working on go-flutter desktop and camera access, and so once that does not use a native window is a perfect fit.
If the code is half done, let me know and i can finish it if you want.

**Comment by Sheharyar566** [comment]
Any progress on this issue?
